
CREATE TABLE [dbo].[HasLicence](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PersonID] [int] NULL,
	[VehicleID] [int] NULL,
 CONSTRAINT [PK_HasLicenceID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[HasLicence]  WITH CHECK ADD  CONSTRAINT [FK_PersonID] FOREIGN KEY([PersonID])
REFERENCES [dbo].[Person] ([ID])
GO

ALTER TABLE [dbo].[HasLicence] CHECK CONSTRAINT [FK_PersonID]
GO

ALTER TABLE [dbo].[HasLicence]  WITH CHECK ADD  CONSTRAINT [FK_VehicleID] FOREIGN KEY([VehicleID])
REFERENCES [dbo].[Vehicle] ([ID])
GO

ALTER TABLE [dbo].[HasLicence] CHECK CONSTRAINT [FK_VehicleID]
GO


